githubRepoOwner: ejoffe
githubRepoName: spr
githubHost: github.com
requireChecks: true
requireApproval: false
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
branchNameIncludeTarget: false
