repoOwner: ejoffe
repoName: spr
forgeHost: github.com
forgeType: github
remote: origin
branch: master
requireChecks: true
requireApproval: false
defaultReviewers: []
mergeMethod: rebase
mergeQueue: false
prTemplateType: stack
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
