name: Release
on:
  push:
    tags:
      - v*
jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          FURY_ORG: ${{ secrets.FURY_ORG }}